module.exports = {
    1: 'Rio de Janeiro',
    2: 'São Paulo',
    3: 'Minas Gerais',
    4: 'Rio Grande do Sul (RS)',
    5: 'Bahia',
    6: 'Pernambuco',
    7: 'Ceará',
    8: 'Amapá e Pará',
    9: 'Paraná',
    10: 'Distrito Federal e Tocantins',
    11: 'Amazonas e Roraima',
    12: 'Santa Catarina (SC)',
    13: 'Paraíba',
    14: 'Acre e Rondônia',
    15: 'Campinas',
    16: 'Maranhão',
    17: 'Espírito Santo',
    18: 'Goiás',
    19: 'Alagoas',
    20: 'Sergipe (SE)',
    21: 'Rio Grande do Norte (RN)',
    22: 'Piauí',
    23: 'Mato Grosso',
    24: 'Mato Grosso do Sul',
};
