module.exports = {
    'TRF1': 'Tribunal Regional Federal da 1ª Região',
    'AC': 'Seção Judiciária do Acre',
    'CZU': 'Subseção Judiciária de Cruzeiro do Sul',
    'AP': 'Seção Judiciária do Amapá',
    'LJI': 'Subseção Judiciária de Laranjal do Jari (AP)',
    'OPQ': 'Subseção Judiciária de Oiapoque (AP)',
    'AM': 'Seção Judiciária do Amazonas',
    'TB': 'Subseção Judiciária de Tabatinga (AM)',
    'TFE': 'Subseção Judiciária de Tefé (AM)',
    'BA': 'Seção Judiciária da Bahia',
    'ALH': 'Subseção Judiciária de Alagoinhas (BA)',
    'BES': 'Subseção Judiciária de Barreiras (BA)',
    'BMP': 'Subseção Judiciária de Bom Jesus da Lapa (BA)',
    'CFS': 'Subseção Judiciária de Campo Formoso (BA)',
    'EUS': 'Subseção Judiciária de Eunápolis (BA)',
    'FSA': 'Subseção Judiciária de Feira de Santana (BA)',
    'GNB': 'Subseção Judiciária de Guanambi (BA)',
    'IL': 'Subseção Judiciária de Ilhéus (BA)',
    'IEE': 'Subseção Judiciária de Irecê (BA)',
    'ITB': 'Subseção Judiciária de Itabuna (BA)',
    'JEE': 'Subseção Judiciária de Jequié (BA)',
    'JZR': 'Subseção Judiciária de Juazeiro (BA)',
    'PAF': 'Subseção Judiciária de Paulo Afonso (BA)',
    'TAF': 'Subseção Judiciária de Teixeira de Freitas (BA)',
    'VCA': 'Subseção Judiciária de Vitória da Conquista (BA)',
    'DF': 'Seção Judiciária do Distrito Federal',
    'GO': 'Seção Judiciária de Goiás',
    'ANS': 'Subseção Judiciária de Anápolis(GO)',
    'ACG': 'Subseção Judiciária de Aparecida de Goiânia(GO)',
    'FRM': 'Subseção Judiciária de Formosa(GO)',
    'IUB': 'Subseção Judiciária de Itumbiara(GO)',
    'JTI': 'Subseção Judiciária de Jataí(GO)',
    'LZA': 'Subseção Judiciária de Luziania(GO)',
    'RVD': 'Subseção Judiciária de Rio Verde(GO)',
    'URC': 'Subseção Judiciária de Uruaçu(GO)',
    'MT': 'Seção Judiciária de Mato Grosso',
    'BAG': 'Subseção Judiciária de Barra do Garças (MT)',
    'CCS': 'Subseção Judiciária de Cáceres (MT)',
    'DIO': 'Subseção Judiciária de Diamantino (MT)',
    'JNA': 'Subseção Judiciária de Juína (MT)',
    'ROI': 'Subseção Judiciária de Rondonópolis (MT)',
    'SNO': 'Subseção Judiciária de Sinop (MT)',
    'MA': 'Seção Judiciária do Maranhão',
    'BBL': 'Subseção Judiciária de Bacabal (MA)',
    'BLA': 'Subseção Judiciária de Balsas (MA)',
    'CXS': 'Subseção Judiciária de Caxias (MA)',
    'IM': 'Subseção Judiciária de Imperatriz (MA)',
    'MG': 'Seção Judiciária de Minas Gerais',
    'CEM': 'Subseção Judiciária de Contagem(MG)',
    'DVL': 'Subseção Judiciária de Divinópolis(MG)',
    'GVS': 'Subseção Judiciária de Governador Valadares(MG)',
    'IIG': 'Subseção Judiciária de Ipatinga(MG)',
    'IUA': 'Subseção Judiciária de Ituiutaba(MG)',
    'JUA': 'Subseção Judiciária de Janaúba(MG)',
    'JF': 'Subseção Judiciária de Juiz de Fora (MG)',
    'LAV': 'Subseção Judiciária de Lavras(MG)',
    'MNC': 'Subseção Judiciária de Manhuaçu(MG)',
    'MCL': 'Subseção Judiciária de Montes Claros (MG)',
    'MRE': 'Subseção Judiciária de Muriaé(MG)',
    'PTU': 'Subseção Judiciária de Paracatu(MG)',
    'PSS': 'Subseção Judiciária de Passos (MG)',
    'PMS': 'Subseção Judiciária de Patos de Minas (MG)',
    'PCS': 'Subseção Judiciária de Poços de Caldas(MG)',
    'PNV': 'Subseção Judiciária de Ponte Nova(MG)',
    'PSA': 'Subseção Judiciária de Pouso Alegre (MG)',
    'SOE': 'Subseção Judiciária de São João Del Rei(MG)',
    'SSP': 'Subseção Judiciária de São Sebastião do Paraíso (MG)',
    'SLA': 'Subseção Judiciária de Sete Lagoas(MG)',
    'TOT': 'Subseção Judiciária de Teófilo Otoni(MG)',
    'UB': 'Subseção Judiciária de Uberaba (MG)',
    'UD': 'Subseção Judiciária de Uberlândia (MG)',
    'UNI': 'Subseção Judiciária de Unaí(MG)',
    'VGA': 'Subseção Judiciária de Varginha(MG)',
    'VCS': 'Subseção Judiciária de Viçosa(MG)',
    'PA': 'Seção Judiciária do Pará',
    'ATM': 'Subseção Judiciária de Altamira(PA)',
    'CAH': 'Subseção Judiciária de Castanhal(PA)',
    'IAB': 'Subseção Judiciária de Itaituba(PA)',
    'MB': 'Subseção Judiciária de Marabá (PA)',
    'PGN': 'Subseção Judiciária de Paragominas(PA)',
    'RDO': 'Subseção Judiciária de Redenção(PA)',
    'ST': 'Subseção Judiciária de Santarém (PA)',
    'TUU': 'Subseção Judiciária de Tucuruí(PA)',
    'PI': 'Seção Judiciária do Piauí',
    'CNT': 'Subseção Judiciária de Corrente (PI)',
    'FLO': 'Subseção Judiciária de Floriano (PI)',
    'PNA': 'Subseção Judiciária de Parnaíba (PI)',
    'PCZ': 'Subseção Judiciária de Picos (PI)',
    'SRN': 'Subseção Judiciária de São Raimundo Nonato (PI)',
    'RO': 'Seção Judiciária de Rondônia',
    'GUM': 'Subseção Judiciária de Guajará-Mirim(RO)',
    'JIP': 'Subseção Judiciária de Ji-paraná(RO)',
    'VHA': 'Subseção Judiciária de Vilhena(RO)',
    'RR': 'Seção Judiciária de Roraima',
    'TO': 'Seção Judiciária de Tocantins',
    'ARN': 'Subseção Judiciária de Araguaína(TO)',
    'GUR': 'Subseção Judiciária de Gurupi(TO)'
};
